name: Deploy Application

on:
  workflow_run:
    workflows: ["publish-docker-images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. GCPì— ë¡œê·¸ì¸
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 3. Google Cloud SDK êµ¬ì„±
      - name: Configure Google Cloud SDK
        run: |
          gcloud --quiet config set project ${{ secrets.GCP_PROJECT_ID }}

      # 4. App Engineì— ì• í”Œë¦¬ì¼€ì´ì…˜ ë°°í¬
      - name: Deploy to App Engine
        run: |
          gcloud app deploy apps/express-server/app.yaml --image-url=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/project/express-server:latest
          gcloud app deploy apps/next-client/app.yaml --image-url=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/project/next-client:latest

      # 5. PRì— ëŒ“ê¸€ ë‚¨ê¸°ê¸°
      - name: Comment on PR
        uses: actions/github-script@v6
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.workflow_run.pull_requests[0].number,
              body: "PR í™•ì¸ ì™„ë£Œ! ë°°í¬ê°€ ì˜ ë§ˆë¬´ë¦¬ ë˜ì—ˆìŠµë‹ˆë‹¤.ğŸ˜"
            })
